// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/ari/v1/agent.proto

package ariv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetInfoRequest is empty for now
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_agent_proto_rawDescGZIP(), []int{0}
}

// GetInfoResponse contains the agent's identity and capabilities
type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DID of the agent (e.g., "did:ainur:agent:math-001")
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version string
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// List of capabilities (e.g., ["math", "arithmetic", "algebra"])
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Runtime information
	RuntimeInfo *RuntimeInfo `protobuf:"bytes,5,opt,name=runtime_info,json=runtimeInfo,proto3" json:"runtime_info,omitempty"`
	// Resource limits
	Limits        *ResourceLimits `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetInfoResponse) GetRuntimeInfo() *RuntimeInfo {
	if x != nil {
		return x.RuntimeInfo
	}
	return nil
}

func (x *GetInfoResponse) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

// RuntimeInfo describes the runtime environment
type RuntimeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime type (e.g., "wasm", "python", "docker")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Runtime version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ResourceLimits defines the agent's resource constraints
type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum memory in MB
	MaxMemoryMb int32 `protobuf:"varint,1,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	// Maximum execution time in milliseconds
	MaxExecutionTimeMs int32 `protobuf:"varint,2,opt,name=max_execution_time_ms,json=maxExecutionTimeMs,proto3" json:"max_execution_time_ms,omitempty"`
	// Maximum concurrent tasks
	MaxConcurrentTasks int32 `protobuf:"varint,3,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceLimits) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetMaxExecutionTimeMs() int32 {
	if x != nil {
		return x.MaxExecutionTimeMs
	}
	return 0
}

func (x *ResourceLimits) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

var File_pkg_ari_v1_agent_proto protoreflect.FileDescriptor

const file_pkg_ari_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/ari/v1/agent.proto\x12\x06ari.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\xdd\x01\n" +
	"\x0fGetInfoResponse\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x126\n" +
	"\fruntime_info\x18\x05 \x01(\v2\x13.ari.v1.RuntimeInfoR\vruntimeInfo\x12.\n" +
	"\x06limits\x18\x06 \x01(\v2\x16.ari.v1.ResourceLimitsR\x06limits\"\xb7\x01\n" +
	"\vRuntimeInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\bmetadata\x18\x03 \x03(\v2!.ari.v1.RuntimeInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x0eResourceLimits\x12\"\n" +
	"\rmax_memory_mb\x18\x01 \x01(\x05R\vmaxMemoryMb\x121\n" +
	"\x15max_execution_time_ms\x18\x02 \x01(\x05R\x12maxExecutionTimeMs\x120\n" +
	"\x14max_concurrent_tasks\x18\x03 \x01(\x05R\x12maxConcurrentTasks2C\n" +
	"\x05Agent\x12:\n" +
	"\aGetInfo\x12\x16.ari.v1.GetInfoRequest\x1a\x17.ari.v1.GetInfoResponseBIZGgithub.com/aidenlippert/zerostate/reference-runtime-v1/pkg/ari/v1;ariv1b\x06proto3"

var (
	file_pkg_ari_v1_agent_proto_rawDescOnce sync.Once
	file_pkg_ari_v1_agent_proto_rawDescData []byte
)

func file_pkg_ari_v1_agent_proto_rawDescGZIP() []byte {
	file_pkg_ari_v1_agent_proto_rawDescOnce.Do(func() {
		file_pkg_ari_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_agent_proto_rawDesc), len(file_pkg_ari_v1_agent_proto_rawDesc)))
	})
	return file_pkg_ari_v1_agent_proto_rawDescData
}

var file_pkg_ari_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_ari_v1_agent_proto_goTypes = []any{
	(*GetInfoRequest)(nil),  // 0: ari.v1.GetInfoRequest
	(*GetInfoResponse)(nil), // 1: ari.v1.GetInfoResponse
	(*RuntimeInfo)(nil),     // 2: ari.v1.RuntimeInfo
	(*ResourceLimits)(nil),  // 3: ari.v1.ResourceLimits
	nil,                     // 4: ari.v1.RuntimeInfo.MetadataEntry
}
var file_pkg_ari_v1_agent_proto_depIdxs = []int32{
	2, // 0: ari.v1.GetInfoResponse.runtime_info:type_name -> ari.v1.RuntimeInfo
	3, // 1: ari.v1.GetInfoResponse.limits:type_name -> ari.v1.ResourceLimits
	4, // 2: ari.v1.RuntimeInfo.metadata:type_name -> ari.v1.RuntimeInfo.MetadataEntry
	0, // 3: ari.v1.Agent.GetInfo:input_type -> ari.v1.GetInfoRequest
	1, // 4: ari.v1.Agent.GetInfo:output_type -> ari.v1.GetInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_ari_v1_agent_proto_init() }
func file_pkg_ari_v1_agent_proto_init() {
	if File_pkg_ari_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_agent_proto_rawDesc), len(file_pkg_ari_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ari_v1_agent_proto_goTypes,
		DependencyIndexes: file_pkg_ari_v1_agent_proto_depIdxs,
		MessageInfos:      file_pkg_ari_v1_agent_proto_msgTypes,
	}.Build()
	File_pkg_ari_v1_agent_proto = out.File
	file_pkg_ari_v1_agent_proto_goTypes = nil
	file_pkg_ari_v1_agent_proto_depIdxs = nil
}
