// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/ari/v1/health.proto

package ariv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents the health state
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING HealthStatus = 2
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_SERVING":     1,
		"HEALTH_STATUS_NOT_SERVING": 2,
		"HEALTH_STATUS_DEGRADED":    3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ari_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_pkg_ari_v1_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ari_v1_health_proto_rawDescGZIP(), []int{0}
}

// HealthCheckRequest is empty for now
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_ari_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_health_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse contains the health status
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ari.v1.HealthStatus" json:"status,omitempty"`
	// Optional message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Active tasks count
	ActiveTasks int32 `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	// Total tasks processed
	TotalTasksProcessed int64 `protobuf:"varint,4,opt,name=total_tasks_processed,json=totalTasksProcessed,proto3" json:"total_tasks_processed,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_ari_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalTasksProcessed() int64 {
	if x != nil {
		return x.TotalTasksProcessed
	}
	return 0
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_pkg_ari_v1_health_proto protoreflect.FileDescriptor

const file_pkg_ari_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/ari/v1/health.proto\x12\x06ari.v1\"\x14\n" +
	"\x12HealthCheckRequest\"\xdb\x01\n" +
	"\x13HealthCheckResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.ari.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x122\n" +
	"\x15total_tasks_processed\x18\x04 \x01(\x03R\x13totalTasksProcessed\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds*\x83\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x032J\n" +
	"\x06Health\x12@\n" +
	"\x05Check\x12\x1a.ari.v1.HealthCheckRequest\x1a\x1b.ari.v1.HealthCheckResponseBIZGgithub.com/aidenlippert/zerostate/reference-runtime-v1/pkg/ari/v1;ariv1b\x06proto3"

var (
	file_pkg_ari_v1_health_proto_rawDescOnce sync.Once
	file_pkg_ari_v1_health_proto_rawDescData []byte
)

func file_pkg_ari_v1_health_proto_rawDescGZIP() []byte {
	file_pkg_ari_v1_health_proto_rawDescOnce.Do(func() {
		file_pkg_ari_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_health_proto_rawDesc), len(file_pkg_ari_v1_health_proto_rawDesc)))
	})
	return file_pkg_ari_v1_health_proto_rawDescData
}

var file_pkg_ari_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ari_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ari_v1_health_proto_goTypes = []any{
	(HealthStatus)(0),           // 0: ari.v1.HealthStatus
	(*HealthCheckRequest)(nil),  // 1: ari.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 2: ari.v1.HealthCheckResponse
}
var file_pkg_ari_v1_health_proto_depIdxs = []int32{
	0, // 0: ari.v1.HealthCheckResponse.status:type_name -> ari.v1.HealthStatus
	1, // 1: ari.v1.Health.Check:input_type -> ari.v1.HealthCheckRequest
	2, // 2: ari.v1.Health.Check:output_type -> ari.v1.HealthCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ari_v1_health_proto_init() }
func file_pkg_ari_v1_health_proto_init() {
	if File_pkg_ari_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_health_proto_rawDesc), len(file_pkg_ari_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ari_v1_health_proto_goTypes,
		DependencyIndexes: file_pkg_ari_v1_health_proto_depIdxs,
		EnumInfos:         file_pkg_ari_v1_health_proto_enumTypes,
		MessageInfos:      file_pkg_ari_v1_health_proto_msgTypes,
	}.Build()
	File_pkg_ari_v1_health_proto = out.File
	file_pkg_ari_v1_health_proto_goTypes = nil
	file_pkg_ari_v1_health_proto_depIdxs = nil
}
