// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/ari/v1/market.proto

package ariv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CFP represents a Call for Proposals
type CFP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique CFP ID
	CfpId string `protobuf:"bytes,1,opt,name=cfp_id,json=cfpId,proto3" json:"cfp_id,omitempty"`
	// Task description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Required capabilities
	Capabilities []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Budget (in some unit, e.g., AINU tokens)
	Budget float64 `protobuf:"fixed64,4,opt,name=budget,proto3" json:"budget,omitempty"`
	// Deadline (Unix timestamp)
	Deadline int64 `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Additional requirements (JSON-encoded)
	Requirements  string `protobuf:"bytes,6,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CFP) Reset() {
	*x = CFP{}
	mi := &file_pkg_ari_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CFP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CFP) ProtoMessage() {}

func (x *CFP) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CFP.ProtoReflect.Descriptor instead.
func (*CFP) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *CFP) GetCfpId() string {
	if x != nil {
		return x.CfpId
	}
	return ""
}

func (x *CFP) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CFP) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CFP) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *CFP) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *CFP) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

// CFPReceipt confirms receipt of a CFP
type CFPReceipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CFP ID (echoed)
	CfpId string `protobuf:"bytes,1,opt,name=cfp_id,json=cfpId,proto3" json:"cfp_id,omitempty"`
	// Whether the agent is interested
	Interested bool `protobuf:"varint,2,opt,name=interested,proto3" json:"interested,omitempty"`
	// Optional message
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CFPReceipt) Reset() {
	*x = CFPReceipt{}
	mi := &file_pkg_ari_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CFPReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CFPReceipt) ProtoMessage() {}

func (x *CFPReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CFPReceipt.ProtoReflect.Descriptor instead.
func (*CFPReceipt) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *CFPReceipt) GetCfpId() string {
	if x != nil {
		return x.CfpId
	}
	return ""
}

func (x *CFPReceipt) GetInterested() bool {
	if x != nil {
		return x.Interested
	}
	return false
}

func (x *CFPReceipt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Bid represents a bid for a CFP
type Bid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CFP ID
	CfpId string `protobuf:"bytes,1,opt,name=cfp_id,json=cfpId,proto3" json:"cfp_id,omitempty"`
	// Agent's DID
	AgentDid string `protobuf:"bytes,2,opt,name=agent_did,json=agentDid,proto3" json:"agent_did,omitempty"`
	// Bid amount
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Estimated execution time in milliseconds
	EstimatedTimeMs int64 `protobuf:"varint,4,opt,name=estimated_time_ms,json=estimatedTimeMs,proto3" json:"estimated_time_ms,omitempty"`
	// Confidence score (0.0 - 1.0)
	Confidence float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Additional proposal details (JSON-encoded)
	Proposal      string `protobuf:"bytes,6,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_pkg_ari_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *Bid) GetCfpId() string {
	if x != nil {
		return x.CfpId
	}
	return ""
}

func (x *Bid) GetAgentDid() string {
	if x != nil {
		return x.AgentDid
	}
	return ""
}

func (x *Bid) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bid) GetEstimatedTimeMs() int64 {
	if x != nil {
		return x.EstimatedTimeMs
	}
	return 0
}

func (x *Bid) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Bid) GetProposal() string {
	if x != nil {
		return x.Proposal
	}
	return ""
}

// BidReceipt confirms receipt of a bid
type BidReceipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bid ID (generated)
	BidId string `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	// CFP ID (echoed)
	CfpId string `protobuf:"bytes,2,opt,name=cfp_id,json=cfpId,proto3" json:"cfp_id,omitempty"`
	// Receipt timestamp
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional message
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidReceipt) Reset() {
	*x = BidReceipt{}
	mi := &file_pkg_ari_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidReceipt) ProtoMessage() {}

func (x *BidReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidReceipt.ProtoReflect.Descriptor instead.
func (*BidReceipt) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *BidReceipt) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *BidReceipt) GetCfpId() string {
	if x != nil {
		return x.CfpId
	}
	return ""
}

func (x *BidReceipt) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidReceipt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_ari_v1_market_proto protoreflect.FileDescriptor

const file_pkg_ari_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/ari/v1/market.proto\x12\x06ari.v1\"\xba\x01\n" +
	"\x03CFP\x12\x15\n" +
	"\x06cfp_id\x18\x01 \x01(\tR\x05cfpId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x01R\x06budget\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\x03R\bdeadline\x12\"\n" +
	"\frequirements\x18\x06 \x01(\tR\frequirements\"]\n" +
	"\n" +
	"CFPReceipt\x12\x15\n" +
	"\x06cfp_id\x18\x01 \x01(\tR\x05cfpId\x12\x1e\n" +
	"\n" +
	"interested\x18\x02 \x01(\bR\n" +
	"interested\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x03Bid\x12\x15\n" +
	"\x06cfp_id\x18\x01 \x01(\tR\x05cfpId\x12\x1b\n" +
	"\tagent_did\x18\x02 \x01(\tR\bagentDid\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12*\n" +
	"\x11estimated_time_ms\x18\x04 \x01(\x03R\x0festimatedTimeMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bproposal\x18\x06 \x01(\tR\bproposal\"r\n" +
	"\n" +
	"BidReceipt\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x15\n" +
	"\x06cfp_id\x18\x02 \x01(\tR\x05cfpId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2e\n" +
	"\x06Market\x12-\n" +
	"\n" +
	"ReceiveCFP\x12\v.ari.v1.CFP\x1a\x12.ari.v1.CFPReceipt\x12,\n" +
	"\tSubmitBid\x12\v.ari.v1.Bid\x1a\x12.ari.v1.BidReceiptBIZGgithub.com/aidenlippert/zerostate/reference-runtime-v1/pkg/ari/v1;ariv1b\x06proto3"

var (
	file_pkg_ari_v1_market_proto_rawDescOnce sync.Once
	file_pkg_ari_v1_market_proto_rawDescData []byte
)

func file_pkg_ari_v1_market_proto_rawDescGZIP() []byte {
	file_pkg_ari_v1_market_proto_rawDescOnce.Do(func() {
		file_pkg_ari_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_market_proto_rawDesc), len(file_pkg_ari_v1_market_proto_rawDesc)))
	})
	return file_pkg_ari_v1_market_proto_rawDescData
}

var file_pkg_ari_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_ari_v1_market_proto_goTypes = []any{
	(*CFP)(nil),        // 0: ari.v1.CFP
	(*CFPReceipt)(nil), // 1: ari.v1.CFPReceipt
	(*Bid)(nil),        // 2: ari.v1.Bid
	(*BidReceipt)(nil), // 3: ari.v1.BidReceipt
}
var file_pkg_ari_v1_market_proto_depIdxs = []int32{
	0, // 0: ari.v1.Market.ReceiveCFP:input_type -> ari.v1.CFP
	2, // 1: ari.v1.Market.SubmitBid:input_type -> ari.v1.Bid
	1, // 2: ari.v1.Market.ReceiveCFP:output_type -> ari.v1.CFPReceipt
	3, // 3: ari.v1.Market.SubmitBid:output_type -> ari.v1.BidReceipt
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_ari_v1_market_proto_init() }
func file_pkg_ari_v1_market_proto_init() {
	if File_pkg_ari_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_market_proto_rawDesc), len(file_pkg_ari_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ari_v1_market_proto_goTypes,
		DependencyIndexes: file_pkg_ari_v1_market_proto_depIdxs,
		MessageInfos:      file_pkg_ari_v1_market_proto_msgTypes,
	}.Build()
	File_pkg_ari_v1_market_proto = out.File
	file_pkg_ari_v1_market_proto_goTypes = nil
	file_pkg_ari_v1_market_proto_depIdxs = nil
}
