// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/ari/v1/market.proto

package ariv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Market_ReceiveCFP_FullMethodName = "/ari.v1.Market/ReceiveCFP"
	Market_SubmitBid_FullMethodName  = "/ari.v1.Market/SubmitBid"
)

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Market service handles CFP (Call for Proposals) and bidding
type MarketClient interface {
	// ReceiveCFP receives a CFP from an orchestrator
	ReceiveCFP(ctx context.Context, in *CFP, opts ...grpc.CallOption) (*CFPReceipt, error)
	// SubmitBid submits a bid for a CFP
	SubmitBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*BidReceipt, error)
}

type marketClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketClient(cc grpc.ClientConnInterface) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) ReceiveCFP(ctx context.Context, in *CFP, opts ...grpc.CallOption) (*CFPReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CFPReceipt)
	err := c.cc.Invoke(ctx, Market_ReceiveCFP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketClient) SubmitBid(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*BidReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidReceipt)
	err := c.cc.Invoke(ctx, Market_SubmitBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
// All implementations must embed UnimplementedMarketServer
// for forward compatibility.
//
// Market service handles CFP (Call for Proposals) and bidding
type MarketServer interface {
	// ReceiveCFP receives a CFP from an orchestrator
	ReceiveCFP(context.Context, *CFP) (*CFPReceipt, error)
	// SubmitBid submits a bid for a CFP
	SubmitBid(context.Context, *Bid) (*BidReceipt, error)
	mustEmbedUnimplementedMarketServer()
}

// UnimplementedMarketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketServer struct{}

func (UnimplementedMarketServer) ReceiveCFP(context.Context, *CFP) (*CFPReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveCFP not implemented")
}
func (UnimplementedMarketServer) SubmitBid(context.Context, *Bid) (*BidReceipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBid not implemented")
}
func (UnimplementedMarketServer) mustEmbedUnimplementedMarketServer() {}
func (UnimplementedMarketServer) testEmbeddedByValue()                {}

// UnsafeMarketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServer will
// result in compilation errors.
type UnsafeMarketServer interface {
	mustEmbedUnimplementedMarketServer()
}

func RegisterMarketServer(s grpc.ServiceRegistrar, srv MarketServer) {
	// If the following call pancis, it indicates UnimplementedMarketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Market_ServiceDesc, srv)
}

func _Market_ReceiveCFP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CFP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).ReceiveCFP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_ReceiveCFP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).ReceiveCFP(ctx, req.(*CFP))
	}
	return interceptor(ctx, in, info, handler)
}

func _Market_SubmitBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).SubmitBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Market_SubmitBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).SubmitBid(ctx, req.(*Bid))
	}
	return interceptor(ctx, in, info, handler)
}

// Market_ServiceDesc is the grpc.ServiceDesc for Market service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Market_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ari.v1.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveCFP",
			Handler:    _Market_ReceiveCFP_Handler,
		},
		{
			MethodName: "SubmitBid",
			Handler:    _Market_SubmitBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/ari/v1/market.proto",
}
