// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/ari/v1/task.proto

package ariv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus represents the current state of a task
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ari_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_ari_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ari_v1_task_proto_rawDescGZIP(), []int{0}
}

// TaskExecuteRequest contains the task to execute
type TaskExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique task ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Task input (JSON-encoded)
	Input string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Timeout in milliseconds (0 = use default)
	TimeoutMs int32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Maximum memory in MB (0 = use default)
	MaxMemoryMb   int32 `protobuf:"varint,4,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskExecuteRequest) Reset() {
	*x = TaskExecuteRequest{}
	mi := &file_pkg_ari_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecuteRequest) ProtoMessage() {}

func (x *TaskExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecuteRequest.ProtoReflect.Descriptor instead.
func (*TaskExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecuteRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TaskExecuteRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskExecuteRequest) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

// TaskExecuteResponse contains the execution result or progress update
type TaskExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task ID (echoed from request)
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Status of the task
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ari.v1.TaskStatus" json:"status,omitempty"`
	// Result (JSON-encoded, only present when status = COMPLETED)
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Error message (only present when status = FAILED)
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Execution time in milliseconds
	ExecutionMs int64 `protobuf:"varint,5,opt,name=execution_ms,json=executionMs,proto3" json:"execution_ms,omitempty"`
	// Progress update (0.0 - 1.0, optional)
	Progress float32 `protobuf:"fixed32,6,opt,name=progress,proto3" json:"progress,omitempty"`
	// Progress message (optional)
	ProgressMessage string `protobuf:"bytes,7,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskExecuteResponse) Reset() {
	*x = TaskExecuteResponse{}
	mi := &file_pkg_ari_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskExecuteResponse) ProtoMessage() {}

func (x *TaskExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ari_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskExecuteResponse.ProtoReflect.Descriptor instead.
func (*TaskExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ari_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskExecuteResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskExecuteResponse) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskExecuteResponse) GetExecutionMs() int64 {
	if x != nil {
		return x.ExecutionMs
	}
	return 0
}

func (x *TaskExecuteResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskExecuteResponse) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

var File_pkg_ari_v1_task_proto protoreflect.FileDescriptor

const file_pkg_ari_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/ari/v1/task.proto\x12\x06ari.v1\"\x86\x01\n" +
	"\x12TaskExecuteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12\"\n" +
	"\rmax_memory_mb\x18\x04 \x01(\x05R\vmaxMemoryMb\"\xf2\x01\n" +
	"\x13TaskExecuteResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.ari.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\fexecution_ms\x18\x05 \x01(\x03R\vexecutionMs\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x02R\bprogress\x12)\n" +
	"\x10progress_message\x18\a \x01(\tR\x0fprogressMessage*\x8e\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x042L\n" +
	"\x04Task\x12D\n" +
	"\aExecute\x12\x1a.ari.v1.TaskExecuteRequest\x1a\x1b.ari.v1.TaskExecuteResponse0\x01BIZGgithub.com/aidenlippert/zerostate/reference-runtime-v1/pkg/ari/v1;ariv1b\x06proto3"

var (
	file_pkg_ari_v1_task_proto_rawDescOnce sync.Once
	file_pkg_ari_v1_task_proto_rawDescData []byte
)

func file_pkg_ari_v1_task_proto_rawDescGZIP() []byte {
	file_pkg_ari_v1_task_proto_rawDescOnce.Do(func() {
		file_pkg_ari_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_task_proto_rawDesc), len(file_pkg_ari_v1_task_proto_rawDesc)))
	})
	return file_pkg_ari_v1_task_proto_rawDescData
}

var file_pkg_ari_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ari_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ari_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),             // 0: ari.v1.TaskStatus
	(*TaskExecuteRequest)(nil),  // 1: ari.v1.TaskExecuteRequest
	(*TaskExecuteResponse)(nil), // 2: ari.v1.TaskExecuteResponse
}
var file_pkg_ari_v1_task_proto_depIdxs = []int32{
	0, // 0: ari.v1.TaskExecuteResponse.status:type_name -> ari.v1.TaskStatus
	1, // 1: ari.v1.Task.Execute:input_type -> ari.v1.TaskExecuteRequest
	2, // 2: ari.v1.Task.Execute:output_type -> ari.v1.TaskExecuteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ari_v1_task_proto_init() }
func file_pkg_ari_v1_task_proto_init() {
	if File_pkg_ari_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ari_v1_task_proto_rawDesc), len(file_pkg_ari_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ari_v1_task_proto_goTypes,
		DependencyIndexes: file_pkg_ari_v1_task_proto_depIdxs,
		EnumInfos:         file_pkg_ari_v1_task_proto_enumTypes,
		MessageInfos:      file_pkg_ari_v1_task_proto_msgTypes,
	}.Build()
	File_pkg_ari_v1_task_proto = out.File
	file_pkg_ari_v1_task_proto_goTypes = nil
	file_pkg_ari_v1_task_proto_depIdxs = nil
}
