linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gosec
    - ineffassign
    - unconvert
    - misspell
    - gocritic
    - revive
    - bodyclose
    - nilerr
    - nolintlint

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/zerostate
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - deployments

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
