#!/bin/bash

# Deploy ZeroState Frontend to Vercel
# This script deploys the web UI to Vercel with proper configuration

set -e

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║        🎨 DEPLOYING FRONTEND TO VERCEL 🎨                    ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Step 1: Check prerequisites
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📋 Step 1/6: Checking Prerequisites${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo -e "${RED}❌ Vercel CLI not installed!${NC}"
    echo -e "${YELLOW}Install with: npm install -g vercel${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Vercel CLI installed${NC}"

# Check if web directory exists
if [ ! -d "web" ]; then
    echo -e "${RED}❌ web/ directory not found!${NC}"
    exit 1
fi
echo -e "${GREEN}✅ web/ directory exists${NC}"

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}⚙️  Step 2/6: Configuration${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Ask for API URL
echo -e "${YELLOW}Enter your backend API URL:${NC}"
echo -e "${YELLOW}(e.g., https://zerostate-api.fly.dev/api/v1)${NC}"
read -p "API URL: " API_URL

if [ -z "$API_URL" ]; then
    echo -e "${RED}❌ API URL is required!${NC}"
    exit 1
fi

echo -e "${GREEN}✅ API URL: $API_URL${NC}"

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🔧 Step 3/6: Creating Configuration Files${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Create vercel.json if it doesn't exist
if [ ! -f "vercel.json" ]; then
    echo -e "${YELLOW}⏳ Creating vercel.json...${NC}"
    cat > vercel.json << 'EOF'
{
  "version": 2,
  "builds": [
    {
      "src": "web/**",
      "use": "@vercel/static"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/web/$1"
    }
  ],
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/web/index.html"
    }
  ],
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=3600, s-maxage=3600"
        }
      ]
    },
    {
      "source": "/(.*)\\.html",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=0, must-revalidate"
        }
      ]
    }
  ]
}
EOF
    echo -e "${GREEN}✅ vercel.json created${NC}"
else
    echo -e "${GREEN}✅ vercel.json already exists${NC}"
fi

# Create .env file for frontend
echo -e "${YELLOW}⏳ Creating web/.env...${NC}"
cat > web/.env << EOF
API_BASE_URL=$API_URL
EOF
echo -e "${GREEN}✅ web/.env created${NC}"

# Update API URL in JavaScript files
echo -e "${YELLOW}⏳ Updating API configuration in web files...${NC}"

# Create or update config.js
cat > web/config.js << EOF
// Auto-generated by deploy-frontend.sh
const API_BASE_URL = '$API_URL';
EOF

echo -e "${GREEN}✅ API configuration updated${NC}"

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🧪 Step 4/6: Testing API Connection${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "${YELLOW}🧪 Testing API health endpoint...${NC}"
if curl -f "${API_URL%/api/v1}/health" 2>/dev/null | grep -q "ok"; then
    echo -e "${GREEN}✅ API is reachable and healthy!${NC}"
else
    echo -e "${RED}⚠️  Warning: API health check failed${NC}"
    echo -e "${YELLOW}Make sure your backend is deployed and accessible${NC}"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🚀 Step 5/6: Deploying to Vercel${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Deploy to Vercel
cd web
echo -e "${YELLOW}⏳ Deploying to Vercel...${NC}"
echo -e "${YELLOW}(You may be prompted to login or configure your project)${NC}"
echo ""

vercel --prod

VERCEL_URL=$(vercel ls | grep "zerostate" | awk '{print $2}' | head -1)

cd ..

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🔐 Step 6/6: Update Backend CORS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [ -n "$VERCEL_URL" ]; then
    echo -e "${YELLOW}📝 Your frontend URL: https://$VERCEL_URL${NC}"
    echo ""
    echo -e "${YELLOW}🔐 Update backend CORS settings:${NC}"
    echo ""
    echo -e "${BLUE}For Fly.io:${NC}"
    echo "  fly secrets set ALLOWED_ORIGINS='https://$VERCEL_URL' --app zerostate-api"
    echo ""
    echo -e "${BLUE}For Render:${NC}"
    echo "  Add ALLOWED_ORIGINS='https://$VERCEL_URL' in environment variables"
    echo ""
    
    read -p "Do you want to update Fly.io CORS now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if command -v fly &> /dev/null; then
            fly secrets set ALLOWED_ORIGINS="https://$VERCEL_URL" --app zerostate-api
            echo -e "${GREEN}✅ CORS updated!${NC}"
        else
            echo -e "${YELLOW}⚠️  Fly CLI not found, please update manually${NC}"
        fi
    fi
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}║        ✨ FRONTEND DEPLOYMENT COMPLETE! ✨                    ║${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}📍 Your ZeroState App:${NC}"
if [ -n "$VERCEL_URL" ]; then
    echo "  Frontend: https://$VERCEL_URL"
fi
echo "  Backend:  $API_URL"
echo ""
echo -e "${YELLOW}🧪 Test Your App:${NC}"
echo "  1. Visit your frontend URL"
echo "  2. Sign up for an account"
echo "  3. Submit a test task"
echo "  4. Check the results!"
echo ""
echo -e "${GREEN}🎉 Your ZeroState platform is now LIVE!${NC}"
